#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

$HOME/.config/polybar/launch.sh
#feh --bg-scale Pictures/wallpaper/vinoth-ragunathan-96670-unsplash.jpg  
feh --bg-tile Pictures/patterns/\'6b7e172c.png\'

bspc config border_width         5
bspc config window_gap          20
bspc config top_padding 		0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#D8DEE8
bspc config normal_border_color \#50586B

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Spotify desktop='^10' follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#bspc rule -a Termite state=floating
